
[env]
TERM = 'xterm-256color'

[window]
padding.x = 8
padding.y = 8 
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
vi_mode_style = { shape = "Underline", blinking = "On" }

[general]
import = [
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
