vim.keymap.set("n", "<leader>s", ":w<CR>", {})
vim.keymap.set("n", "<leader>M", ":Mason<CR>", {})
vim.keymap.set("n", "Q", ":q!<CR>", {})
vim.keymap.set({ "i" }, "jk", "<Esc>", { silent = true })
vim.keymap.set("v", ",", "<Esc>")
vim.keymap.set("n", "<leader>v", ":vs<CR>")
vim.keymap.set("n", "<leader>vs", ":sp<CR>")
vim.keymap.set("n", "W", "<C-w>", { silent = true })
vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
