require("config.lazy")
require("config.lsp")
require("config.keymaps")
require("config.options")
require("config.autocmds")
require("config.usercmds")
require("fzf-lua").register_ui_select()
require("local.term")
