-- return {
-- 	{
-- 		"folke/noice.nvim",
-- 		event = "VeryLazy",
-- 		dependencies = {
-- 			"MunifTanjim/nui.nvim",
-- 			"rcarriga/nvim-notify",
-- 		},
-- 		opts = {
-- 			lsp = {
-- 				override = {
-- 					["vim.lsp.util.convert_input_to_markdown_lines"] = true,
-- 					["vim.lsp.util.stylize_markdown"] = true,
-- 					["cmp.entry.get_documentation"] = true,
-- 				},
-- 				progress = {
-- 					enabled = true,
-- 					format = "lsp_progress",
-- 					format_done = "lsp_progress_done",
-- 					throttle = 1000 / 30,
-- 				},
-- 			},
-- 			presets = {
-- 				bottom_search = true,
-- 				command_palette = true,
-- 				long_message_to_split = true,
-- 				inc_rename = true,
-- 				lsp_doc_border = true,
-- 			},
-- 			routes = {
-- 				{
-- 					filter = {
-- 						event = "notify",
-- 						find = "No information available",
-- 					},
-- 					opts = {
-- 						skip = true,
-- 					},
-- 				},
-- 				{
-- 					filter = {
-- 						event = "notify",
-- 						find = "No code actions available",
-- 					},
-- 					opts = {
-- 						skip = true,
-- 					},
-- 				},
-- 				{
-- 					filter = {
-- 						event = "msg_show",
-- 						find = "written",
-- 					},
-- 					opts = {
-- 						skip = true,
-- 					},
-- 				},
-- 			},
-- 		},
-- 	},
-- }
return {}
